[package]
name = "taceo-ark-algebra"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Optimized multi-scalar multiplication and FFT routines for arkworks-rs curves and fields, generic enough to also work on secret-shared values."
readme = "./README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["arkworks", "msm", "fft", "zero-knowledge", "zk"]
exclude = [".gitignore"]

[dependencies]
ark-ec.workspace = true
ark-ff.workspace = true
ark-poly.workspace = true
ark-std.workspace = true
rayon.workspace = true

[[bench]]
harness = false
name = "algebra"

[dev-dependencies]
ark-bls12-381.workspace = true
ark-bn254.workspace = true
# The benchmarks compare against the arkworks implementations, which have to run with rayon for
# the comparison to be fair.
ark-ec = { workspace = true, features = ["std", "parallel"] }
ark-poly = { workspace = true, features = ["std", "parallel"] }
criterion = "0.8"
rand.workspace = true
